---  
- name: RHEL7 Ansible STIG
  hosts: stig # enter hostnames here
  become: yes
  # updates: Needs to be Tested
        # V-71929
  vars:  
    rhel7_checklist_name: Ansible_RHEL7_v2r6_20200124.ckl
    # V-71929
    vuln_id_mapping_: 20
    var_accounts_maximum_age_login_defs: 60 #true
  tasks:
    - name: Set LDAP to be used for authentication
      lineinfile:
        path: /etc/sysconfig/authconfig
        regexp: ^USELDAPAUTH=
        line: USELDAPAUTH=yes
        create: true
      when:
      - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
    
    
    
      tags:
      - sssd_ldap_start_tls
      - medium_severity
      - unknown_strategy
      - low_complexity
      - medium_disruption
      - no_reboot_needed
      - CCE-80546-5
      - NIST-800-53-AC-17(2)
      - NIST-800-53-CM-7
      - DISA-STIG-RHEL-07-040180
      - V-72227
    
    - name: Test for domain group
      command: grep '\s*\[domain\/[^]]*]' /etc/sssd/sssd.conf
      register: test_grep_domain
      ignore_errors: true
      changed_when: false
      when:
      - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
    
    
    
      tags:
      - sssd_ldap_start_tls
      - medium_severity
      - unknown_strategy
      - low_complexity
      - medium_disruption
      - no_reboot_needed
      - CCE-80546-5
      - NIST-800-53-AC-17(2)
      - NIST-800-53-CM-7
      - DISA-STIG-RHEL-07-040180
      - V-72227
    
    - name: Add default domain group and use STARTTLS (if no domain there)
      ini_file:
        path: /etc/sssd/sssd.conf
        section: '{{ item.section }}'
        option: '{{ item.option }}'
        value: '{{ item.value }}'
        create: true
        mode: 384
      with_items:
      - section: sssd
        option: domains
        value: default
      - section: domain/default
        option: id_provider
        value: files
      - section: domain/default
        option: ldap_id_use_start_tls
        value: true
      when:
      - test_grep_domain.stdout is defined
      - test_grep_domain.stdout | length < 1
      - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
    
    
    
      tags:
      - sssd_ldap_start_tls
      - medium_severity
      - unknown_strategy
      - low_complexity
      - medium_disruption
      - no_reboot_needed
      - CCE-80546-5
      - NIST-800-53-AC-17(2)
      - NIST-800-53-CM-7
      - DISA-STIG-RHEL-07-040180
      - V-72227
    
      register: stig_result
      
      
#Conditional

    # # set the xml
    # # if system is configured
    # - name: Set the checklist sections if success {{  vuln_id_mapping_  }}
      # xml:
        # path: /home/u_smerme.ca/ansible/results/{{  rhel7_checklist_name  }}
        # xpath: /CHECKLIST/STIGS/iSTIG/VULN[{{  vuln_id_mapping_  }}]/{{  item.xpath  }}
        # value: "{{  item.value  }}"
      # with_items:
        # - { xpath: 'STATUS', value: 'Not_A_Finding'}
        # - { xpath: 'FINDING_DETAILS', value: 'Configured as required.'}
        # - { xpath: 'COMMENTS', value: 'System prevents a user from overriding the screensaver idle-activation-enabled setting for the graphical user interface. Verification method: Ansible.
 # Verification Method: Ansible.'}
      # when: stig_result.failed
    
    # # If system is NOT configured properly.
    # - name: Set the checklist sections if failed
      # xml:
        # path: /home/u_smerme.ca/ansible/results/{{  rhel7_checklist_name  }}
        # xpath: /CHECKLIST/STIGS/iSTIG/VULN[{{  vuln_id_mapping_  }}]/{{  item.xpath  }}
        # value: "{{  item.value  }}"
      # with_items:
        # - { xpath: 'STATUS', value: 'open'}
        # - { xpath: 'FINDING_DETAILS', value: 'AIDE is not installed.'}
        # - { xpath: 'COMMENTS', value: 'System is not configured to prevent a user from overriding the screensaver idle-activation-enabled setting for the graphical user interface. Verification Method: Ansible.'}
      # when: stig_result.failed == true 

    # xmllint --xpath "/CHECKLIST/STIGS/iSTIG/VULN[231]/STATUS/text()" /home/u_smerme.ca/ansible/results/Ansible_RHEL7_v2r6_20200124.ckl
    # xmllint --xpath "/CHECKLIST/STIGS/iSTIG/VULN[201]/FINDING_DETAILS/text()" /home/u_smerme.ca/ansible/results/Ansible_RHEL7_v2r6_20200124.ckl
    # xmllint --xpath "/CHECKLIST/STIGS/iSTIG/VULN[231]/COMMENTS/text()" /home/u_smerme.ca/ansible/results/Ansible_RHEL7_v2r6_20200124.ckl