---  
- name: RHEL7 Ansible STIG
  hosts: stig # enter hostnames here
  become: yes
  # updates: Needs to be Tested
        # V-73155 #
  vars:  
  tasks:
    - name: Prevent user modification of GNOME lock-delay
    #add logic if not a GNOME, then stig is NOT_Applicable
      lineinfile:
        path: /etc/dconf/db/local.d/locks/00-security-settings-lock
        regexp: ^/org/gnome/desktop/screensaver/lock-delay
        line: /org/gnome/desktop/screensaver/lock-delay
        create: true
      when:
      - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
      tags:
      - dconf_gnome_screensaver_user_locks
      - medium_severity
      - unknown_strategy
      - low_complexity
      - medium_disruption
      - no_reboot_needed
      - CCE-80371-8
      - NIST-800-53-AC-11(a)
      - NIST-800-171-3.1.10
      - DISA-STIG-RHEL-07-010081
      - V-73155