---  
- name: RHEL7 Ansible STIG
  hosts: stig # enter hostnames here
  become: yes
  # updates: Needs to be Tested
        # V-73159 #
  vars:  
    rhel7_checklist_name: Ansible_RHEL7_v2r6_20200124.ckl
    # V-73159
    vuln_id_mapping_: 217
    var_password_pam_retry: 3 #true
  tasks:
    - name: Set Password Retry Prompts Permitted Per-Session - system-auth (change)
      replace:
        dest: /etc/pam.d/system-auth
        follow: true
        regexp: (^.*\spam_pwquality.so\s.*retry\s*=\s*)(\S+)(.*$)
        replace: \g<1>{{ var_password_pam_retry }}\g<3>
    - name: Set Password Retry Prompts Permitted Per-Session - system-auth (add)
      replace:
        dest: /etc/pam.d/system-auth
        follow: true
        regexp: ^.*\spam_pwquality.so\s(?!.*retry\s*=\s*).*$
        replace: \g<0> retry={{ var_password_pam_retry }}
      tags:
      - accounts_password_pam_retry
      - medium_severity
      - configure_strategy
      - low_complexity
      - medium_disruption
      - no_reboot_needed
      - CCE-27160-1
      - NIST-800-53-CM-6(b)
      - NIST-800-53-IA-5(c)
      - CJIS-5.5.3
      - DISA-STIG-RHEL-07-010119
      - V-73159
